version: '3.8'

services:
  tv-recommender:
    build: .
    container_name: tv-recommender
    ports:
      - "5000:5000"  # Map Flask's default port
    volumes:
      - ./data:/app/data  # For persisting recommendations cache
      - .:/app  # Mount current directory for development
    env_file:
      - .env
    restart: unless-stopped 